# Generated by Django 6.0.1 on 2026-04-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userregister_email_userregister_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='picture',
        ),
    ]
